# Generated by Django 2.2.7 on 2019-12-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='million',
            name='dump_v2',
            field=models.TextField(default='dump v2'),
            preserve_default=False,
        ),
    ]
