# Generated by Django 2.2.7 on 2019-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0002_million_dump_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='million',
            name='dump_v2',
            field=models.TextField(null=True),
        ),
    ]
