# Generated by Django 2.2.7 on 2019-12-03 10:20

from django.db import migrations, models
import time
t = time.time()
class Migration(migrations.Migration):

    dependencies = [
        ('million', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='million',
            name='dump_v2',
            field=models.TextField(null=True),
        ),
    ]

print("total time -------",time.time()-t)
